print("    *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
#1
print("    *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("    *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *   *\n  *   *\n  *   *\n  *****")
print("    *     "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)
print('What happends now?')