print("Hola, Python")
print()
print("Este es nuesttro primer programa")
'''Comentario
de varias lineas'''
print(type("SOy un dato de"))
print(type(5))
print(type(5.5))
print(type(3+1j))
print(type(True))
print(type(print("siu")))
print("the bitsy spider\nclimbed up the wall")
print()
#print(\)
print("The itsy bitsy spider","climbed up","the waterspout.")
print("My name is","Python",end=" ")
print("Monty Python")
print("My","name","is","Monty","Python",sep="_")
print("My","name","is",sep="_",end="*")
print("Monty","Python",sep="*",end="*\n")