print("Consulta de tipo de datos")
print("Es un número octal",type(0o12))
print("número hexadecimal",type(0x30))
print("Es un número octal",0o12)
print("Número hexadecimal",0x30)
print("operador del modulo",5%3)
print("operador del exponente",5**2)
print('""""""')
print("el operador de igual")
x=25
print("EL valor de x es de",x)
